-- This is a list with all the keys and the coresponding code.
-- This list exists so we can overide the language and take input directly from the keyboard.
-- Thus, any keyboard layout language should work.
-- Codes may vary accordingn to the keyboard. To find them run xev | grep keycode

-- Default modkey.
-- Usually, Mod4 is the key with a logo between Control and Alt.
-- If you do not like this or do not have such a key,
-- I suggest you to remap Mod4 to another key using xmodmap or other tools.
-- However, you can use another modifier like Mod1, but it may interact with others.
modkey = "Mod4"
-- Keys
key_Volume_Up                 =  "#123" -- Fn+F3
key_Volume_Down               =  "#122" -- Fn+F2
key_Esc                       =  "#9"
key_F1                        =  "#67"
key_F2                        =  "#68"
key_F3                        =  "#69"
key_F4                        =  "#70"
key_F5                        =  "#71"
key_F6                        =  "#72"
key_F7                        =  "#73"
key_F8                        =  "#74"
key_F9                        =  "#75"
key_F10                       =  "#76"
key_F11                       =  "#95"
key_F12                       =  "#96"
key_Scroll_Lock               =  "#78"
key_tilda                     =  "#49"
key_1                         =  "#10"
key_2                         =  "#11"
key_3                         =  "#12"
key_4                         =  "#13"
key_5                         =  "#14"
key_6                         =  "#15"
key_7                         =  "#16"
key_8                         =  "#17"
key_9                         =  "#18"
key_0                         =  "#19"
key_dash                      =  "#20"
key_equal                     =  "#21"
key_Backspace                 =  "#22"
key_Insert                    =  "#118"
key_Home                      =  "#110"
key_Page_Up                   =  "#112"
key_Num_Lock                  =  "#77"
key_KP_slash                  =  "#106"
key_KP_star                   =  "#63"
key_KP_dash                   =  "#82"
key_Tab                       =  "#23"
key_Q                         =  "#24"
key_W                         =  "#25"
key_E                         =  "#26"
key_R                         =  "#27"
key_T                         =  "#28"
key_Y                         =  "#29"
key_U                         =  "#30"
key_I                         =  "#31"
key_O                         =  "#32"
key_P                         =  "#33"
key_open_bracket              =  "#34"
key_close_bracket             =  "#35"
key_Delete                    =  "#119"
key_End                       =  "#115"
key_Page_Down                 =  "#105"
key_KP_7                      =  "#79"
key_KP_8                      =  "#80"
key_KP_9                      =  "#81"
key_KP_plus                   =  "#86"
key_Caps_Lock                 =  "#66"
key_A                         =  "#38"
key_S                         =  "#39"
key_D                         =  "#40"
key_F                         =  "#41"
key_G                         =  "#42"
key_H                         =  "#43"
key_J                         =  "#44"
key_K                         =  "#45"
key_L                         =  "#46"
key_semicolon                 =  "#47"
key_apostrophe                =  "#48"
key_Enter                     =  "#36"
key_KP_4                      =  "#83"
key_KP_5                      =  "#84"
key_KP_6                      =  "#85"
key_Shift_Left                =  "#50"
key_Z                         =  "#52"
key_X                         =  "#53"
key_C                         =  "#54"
key_V                         =  "#55"
key_B                         =  "#56"
key_N                         =  "#57"
key_M                         =  "#58"
key_comma                     =  "#59"
key_period                    =  "#60"
key_slash                     =  "#61"
key_Shift_Right               =  "#62"
key_backslash                 =  "#51"
key_Up                        =  "#111"
key_KP_1                      =  "#87"
key_KP_2                      =  "#88"
key_KP_3                      =  "#89"
key_KP_Enter                  =  "#104"
key_Ctrl_Left                 =  "#37"
key_Alt_Left                  =  "#64"
key_Space                     =  "#65"
key_Alt_Right                 =  "#108"
key_Menu                      =  "#135"
key_Ctrl_Right                =  "#105"
key_Left                      =  "#113"
key_Down                      =  "#116"
key_Right                     =  "#114"
key_KP_0                      =  "#90"
key_KP_period                 =  "#91"
