#!/bin/bash

## Files and cmd
EWW="/home/markos/eww-x11/eww/target/release/eww -c $HOME/.config/eww/awesome"

## Run eww daemon if not running already
if [[ ! $(pidof eww) ]]; then
    ${EWW} daemon
    sleep 1
fi

## Open widgets
# NB_MONITORS=($(hyprctl monitors -j | jq -r '.[] | .id'))
# for i in "${!NB_MONITORS[@]}"; do
    ${EWW} open bar
    # [[ $i == 0 ]] && ${EWW} open-many sidebar notifications
# done
